### PR TITLE
Creed Ford.html

### PR DESCRIPTION
**Pull request by creedatticus**

### CODE REVIEW

**Review by DtheTchyld — APPROVED** [review]
Looks great, might wanna consider putting a picture in, you need to upload it to assets. Go to the root file and then assets, images, and upload your jpg there. You then need to call it in this code here.

**Review by Ethan-Adams-01-05 — APPROVED** [review]
Looks Great! Good Work!

**Comment by creedatticus** [comment]
hey Derek, I have no idea what you mean lol. what's assets and root files? isn't it already posted on the website?

**Comment by creedatticus** [comment]
oh wait, I think you meant to upload pictures

**Pull request merged**
